M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date Thu 09 Feb 2023 07:40:42 AM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-09T07:40:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.28Y-2.05
X3.28Y-3.84
X4.4Y-2.05
X4.4Y-3.84
T0
M30
